name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '13,57 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |-
        pip install -r requirements.txt
    - name: Fetch latest data
      run: |-
        if [[ -f "wanted.json" ]]; then cp wanted.json wanted-old.json; fi;
        python scrape.py
        if [[ -f "wanted-old.json" ]]; then csv-diff wanted-old.json wanted.json --key=uid --singular=person --plural=people > message.txt; fi;
        git-history file wanted.db wanted.json --branch master --namespace wanted --id uid
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add wanted.json wanted.db
        timestamp=$(date -u)
        if [[ -f "message.txt" ]]; then git commit -F message.txt || exit 0; else git commit -m "Latest data: ${timestamp}" || exit 0; fi
        git push
